/** Curated, categorised icons for the picker — illustration-tool oriented, so
 * the common drawing/editing actions are easy to find without searching. Each
 * value is a Tabler component name (the stored `icon` value, e.g. "IconBrush").
 * The full ~6000 Tabler set stays searchable below via the search box. */
export interface IconCategory {
  /** JA source key (translated via i18n like everything else). */
  label: string;
  icons: string[];
}

/** Preset operation colours (button fill on the figure + pie slice + icon tint).
 * A small, curated set that reads on both light and dark backgrounds; absent =
 * inherit the default highlight colour. Labelled so they show in the picker. */
export const OP_COLOR_PRESETS: { label: string; hex: string }[] = [
  { label: "レッド", hex: "#ef4444" },
  { label: "オレンジ", hex: "#f59e0b" },
  { label: "イエロー", hex: "#eab308" },
  { label: "グリーン", hex: "#22c55e" },
  { label: "ティール", hex: "#14b8a6" },
  { label: "ブルー", hex: "#3b82f6" },
  { label: "パープル", hex: "#8b5cf6" },
  { label: "ピンク", hex: "#ec4899" },
];

export const ICON_CATEGORIES: IconCategory[] = [
  {
    label: "描画・ペン",
    icons: [
      "IconBrush",
      "IconBrushOff",
      "IconPencil",
      "IconPencilPlus",
      "IconPencilMinus",
      "IconBallpen",
      "IconWriting",
      "IconSignature",
      "IconScribble",
      "IconHighlight",
      "IconSpray",
      "IconPaint",
      "IconChalkboard",
      "IconFeather",
      "IconEraser",
    ],
  },
  {
    label: "色",
    icons: [
      "IconPalette",
      "IconColorPicker",
      "IconColorPickerOff",
      "IconColorSwatch",
      "IconColorFilter",
      "IconBucketDroplet",
      "IconBucket",
      "IconDroplet",
      "IconDropletFilled",
      "IconDropletHalf",
      "IconPaintOff",
      "IconContrast",
      "IconContrast2",
      "IconBrightness",
      "IconSunHigh",
      "IconMoon",
      "IconBulb",
      "IconWand",
      "IconGradienter",
      "IconFlare",
    ],
  },
  {
    label: "選択・変形",
    icons: [
      "IconLasso",
      "IconLassoPolygon",
      "IconSelect",
      "IconSelectAll",
      "IconMarquee2",
      "IconCrop",
      "IconFrame",
      "IconViewfinder",
      "IconArrowsMove",
      "IconResize",
      "IconArrowsDiagonal",
      "IconArrowsMinimize",
      "IconArrowAutofitWidth",
      "IconArrowAutofitHeight",
      "IconRotate",
      "IconRotate2",
      "IconRotateClockwise",
      "IconRotate360",
      "IconFlipHorizontal",
      "IconFlipVertical",
      "IconTransform",
      "IconPerspective",
    ],
  },
  {
    label: "パス・図形",
    icons: [
      "IconVector",
      "IconVectorBezier2",
      "IconVectorSpline",
      "IconVectorTriangle",
      "IconSquare",
      "IconSquareRotated",
      "IconRectangle",
      "IconRectangleVertical",
      "IconCircle",
      "IconCircleFilled",
      "IconOval",
      "IconTriangle",
      "IconTriangleInverted",
      "IconLine",
      "IconPolygon",
      "IconPentagon",
      "IconHexagon",
      "IconStar",
      "IconStarFilled",
      "IconStarHalf",
      "IconHeart",
      "IconDiamond",
      "IconSlash",
      "IconPointFilled",
      "IconShape",
      "IconShape2",
    ],
  },
  {
    label: "表示・ナビ",
    icons: [
      "IconZoomIn",
      "IconZoomOut",
      "IconZoomReset",
      "IconZoomInArea",
      "IconHandStop",
      "IconHandFinger",
      "IconEye",
      "IconEyeOff",
      "IconGrid3x3",
      "IconGridDots",
      "IconGrid4x4",
      "IconGridPattern",
      "IconLayoutGrid",
      "IconLayout",
      "IconLayout2",
      "IconRuler",
      "IconRuler2",
      "IconRulerMeasure",
      "IconFocusCentered",
      "IconCurrentLocation",
      "IconMaximize",
      "IconMinimize",
      "IconArrowsMaximize",
      "IconAperture",
      "IconTargetArrow",
      "IconBlur",
    ],
  },
  {
    label: "レイヤー",
    icons: [
      "IconStack",
      "IconStack2",
      "IconStack3",
      "IconStackForward",
      "IconStackBackward",
      "IconStackPop",
      "IconStackPush",
      "IconLayersIntersect",
      "IconLayersSubtract",
      "IconLayersUnion",
      "IconLayersDifference",
      "IconLayersLinked",
      "IconLayersOff",
      "IconFolder",
      "IconFolderOpen",
      "IconFolderPlus",
    ],
  },
  {
    label: "編集・履歴",
    icons: [
      "IconArrowBackUp",
      "IconArrowForwardUp",
      "IconRefresh",
      "IconRestore",
      "IconCopy",
      "IconCopyPlus",
      "IconClipboard",
      "IconClipboardCopy",
      "IconClipboardCheck",
      "IconClipboardPlus",
      "IconCut",
      "IconScissors",
      "IconTrash",
      "IconTrashX",
    ],
  },
  {
    label: "文字",
    icons: [
      "IconTypography",
      "IconTextSize",
      "IconTextResize",
      "IconLetterA",
      "IconLetterCase",
      "IconBold",
      "IconItalic",
      "IconUnderline",
      "IconAlignLeft",
      "IconAlignCenter",
      "IconAlignRight",
    ],
  },
  {
    label: "メディア・再生",
    icons: [
      "IconPlayerPlay",
      "IconPlayerPause",
      "IconPlayerStop",
      "IconPlayerRecord",
      "IconPlayerSkipBack",
      "IconPlayerSkipForward",
      "IconVolume",
      "IconVolume2",
      "IconVolume3",
      "IconMusic",
      "IconMovie",
      "IconVideo",
      "IconCamera",
      "IconMicrophone",
    ],
  },
  {
    label: "矢印・方向",
    icons: [
      "IconArrowUp",
      "IconArrowDown",
      "IconArrowLeft",
      "IconArrowRight",
      "IconArrowUpRight",
      "IconCornerUpLeft",
      "IconChevronUp",
      "IconChevronDown",
      "IconChevronLeft",
      "IconChevronRight",
      "IconArrowsHorizontal",
      "IconArrowsVertical",
      "IconArrowBigUp",
      "IconArrowBigDown",
    ],
  },
  {
    label: "ツール・記号",
    icons: [
      "IconTool",
      "IconTools",
      "IconMagnet",
      "IconBolt",
      "IconFlame",
      "IconBookmark",
      "IconTag",
      "IconFlag",
      "IconBell",
      "IconThumbUp",
      "IconLock",
      "IconLockOpen",
      "IconKey",
      "IconSearch",
      "IconFilter",
      "IconHome",
      "IconUser",
      "IconCheck",
      "IconQuestionMark",
      "IconInfoCircle",
      "IconAlertTriangle",
      "IconHash",
      "IconAt",
      "IconWorld",
    ],
  },
  {
    label: "ファイル・その他",
    icons: [
      "IconDeviceFloppy",
      "IconFileExport",
      "IconFileImport",
      "IconPrinter",
      "IconSettings",
      "IconAdjustments",
      "IconPin",
      "IconPlus",
      "IconMinus",
      "IconX",
    ],
  },
];
